#!/usr/bin/env bash

#
# This script has to be used to cleanup a Tango source distrib
# retrived from SVN from the distrib/source/trunk (or tags)
# This is needed, because most of the directories in the source
# distrib are links to other directories in SVN using svn:externals
# property. In these original directories, they are some files 
# which are needed there but not in a source distribution framework
# (Windows specific files....)
#


#
#	cppserver directories
#

rm -Rf cppserver/database/winnt
rm -Rf cppserver/database/win64
rm -f cppserver/database/Makefile
rm -f cppserver/database/README
rm -f cppserver/database/update_db_from_5_to_9.3.4.sql.in
rm -f cppserver/database/update_db_from_6_to_9.3.4.sql.in

rm -Rf cppserver/starter/doc_html
rm -f cppserver/starter/Makefile
rm -f cppserver/starter/StarterService.cpp
rm -f cppserver/starter/StarterService.h
rm -f cppserver/starter/starter.startup
rm -Rf cppserver/starter/vc9_proj
rm -Rf cppserver/starter/vc10_proj

rm -f cppserver/tangoaccesscontrol/Makefile
rm -Rf cppserver/tangoaccesscontrol/scripts
rm -Rf cppserver/tangoaccesscontrol/vcproj
rm -Rf cppserver/tangoaccesscontrol/vc10_proj

rm -f cppserver/tangotest/Makefile
rm -Rf cppserver/tangotest/doc_html
rm -Rf cppserver/tangotest/win32
rm -Rf cppserver/tangotest/win64
rm -f cppserver/tangotest/Doxyfile
rm -f cppserver/tangotest/pom.xml
rm -f cppserver/tangotest/TangoClassID.txt

#
#	lib directories
#


rm -f lib/cpp/client/README
rm -Rf lib/cpp/server/winnt_lib
rm -f lib/cpp/server/idl/idl2cpp
rm -f lib/cpp/server/idl/*.cpp
rm -f lib/cpp/server/idl/*.h
rm -f cpp/lib/server/w32win.cpp
rm -f cpp/lib/server/w32win.h
rm -f lib/cpp/server/ntservice.cpp

rm -f lib/idl/idl2cpp

rm -Rf lib/cpp/log4tango/autom4te.cache
rm -f lib/cpp/log4tango/make-install.sh
rm -Rf lib/cpp/log4tango/msvc8
rm -Rf lib/cpp/log4tango/msvc9
rm -Rf lib/cpp/log4tango/ms32vc10
rm -Rf lib/cpp/log4tango/ms64vc9
rm -Rf lib/cpp/log4tango/ms64vc10
rm -Rf lib/cpp/log4tango/ms64vc11
rm -Rf lib/cpp/log4tango/ms64vc12

#
#	utils directories
#

rm -f utils/notifd2db/Makefile
rm -Rf utils/notifd2db/winnt

rm -f utils/tango_admin/Makefile


