/* DO NOT EDIT THIS FILE - it is machine generated */
/*
    Copyright (c) 2007-2013 iMatix Corporation

    This file is part of 0MQ.

    0MQ is free software; you can redistribute it and/or modify it under
    the terms of the Lesser GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    0MQ is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    Lesser GNU General Public License for more details.

    You should have received a copy of the Lesser GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#include <jni.h>
/* Header for class org_zeromq_ZMQ_Context */

#ifndef _Included_org_zeromq_ZMQ_Context
#define _Included_org_zeromq_ZMQ_Context
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_ZMQ_Context
 * Method:    construct
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_ZMQ_00024Context_construct
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_zeromq_ZMQ_Context
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_zeromq_ZMQ_00024Context_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
