#!/usr/bin/env bash

#
# This script has to be used to cleanup a Tango source distrib
# retrived from SVN from the distrib/source/trunk (or tags)
# This is needed, because most of the directories in the source
# distrib are links to other directories in SVN using svn:externals
# property. In these original directories, they are some files 
# which are needed there but not in a source distribution framework
#


#
#	cppserver directories
#

rm -Rf cppserver/database/winnt
rm -f cppserver/database/Makefile
rm -f cppserver/database/README

rm -Rf cppserver/starter/doc_html
rm -f cppserver/starter/Makefile
rm -f cppserver/starter/StarterService.cpp
rm -f cppserver/starter/StarterService.h
rm -f cppserver/starter/starter.startup
rm -Rf cppserver/starter/vc9_proj

rm -f cppserver/tangoaccesscontrol/Makefile
rm -Rf cppserver/tangoaccesscontrol/scripts
rm -Rf cppserver/tangoaccesscontrol/vcproj

rm -f cppserver/tangotest/Makefile
rm -Rf cppserver/tangotest/doc_html
rm -Rf cppserver/tangotest/win32
rm -f cppserver/tangotest/Doxyfile
rm -f cppserver/tangotest/pom.xml
rm -f cppserver/tangotest/TangoClassID.txt

#
#	doc directories
#

rm -f doc/src/grep_lyx
rm -f doc/src/install_all
rm -f doc/src/replace
rm -f doc/src/Replace.class
rm -f doc/src/tango_latex2html

rm -f doc/src/advanced/alarm.fig
rm -f doc/src/advanced/att_lock.*
rm -f doc/src/advanced/DevTestClass.*
rm -f doc/src/advanced/events.*
rm -f doc/src/advanced/ext_*
rm -f doc/src/advanced/line.tex
rm -f doc/src/advanced/main*

rm -f doc/src/appendix/serv.res

rm -Rf doc/src/atk/examples

rm -f doc/src/cpp_api/asyn_*
rm -f doc/src/cpp_api/attr.*
rm -f doc/src/cpp_api/extract.*
rm -f doc/src/cpp_api/line.lyx
rm -f doc/src/cpp_api/NamedExcept.cpp
rm -f doc/src/cpp_api/nb.*

rm -f doc/src/dance/Ready.fig

rm -f doc/src/ds_model/archi.gif

rm -Rf doc/src/ds_writing/advanced
rm -f doc/src/ds_writing/circle.tex
rm -f doc/src/ds_writing/circle.fig
rm -f doc/src/ds_writing/circle.jpg
rm -Rf doc/src/ds_writing/compiling
rm -f doc/src/ds_writing/complete_server.fig
rm -f doc/src/ds_writing/complete_server.jpg
rm -Rf doc/src/ds_writing/cpp_exchanging
rm -Rf doc/src/ds_writing/cpp_started
rm -Rf doc/src/ds_writing/dance
rm -f doc/src/ds_writing/device_et.fig
rm -f doc/src/ds_writing/device_et.jpg
rm -f doc/src/ds_writing/ESRFlogo.tex
rm -f doc/src/ds_writing/images.tex
rm -Rf doc/src/ds_writing/java_exchanging
rm -Rf doc/src/ds_writing/java_started
rm -f doc/src/ds_writing/line.lyx
rm -Rf doc/src/ds_writing/logging
rm -Rf doc/src/ds_writing/model
rm -Rf doc/src/ds_writing/nt_server
rm -f doc/src/ds_writing/r_attributes.fig
rm -f doc/src/ds_writing/startup.fig
rm -f doc/src/ds_writing/startup.jpg
rm -f doc/src/ds_writing/w_attribute.fig
rm -Rf doc/src/ds_writing/writing
rm -Rf doc/src/ds_writing/writing_java

rm -f doc/src/gen_api/line.lyx

rm -f doc/src/java_api/line.lyx
rm -f doc/src/java_api/picture/architecture.fig
rm -f doc/src/java_api/picture/architecture1.fig
rm -f doc/src/java_api/picture/Newline.*

rm -f doc/src/layouts/stdsections.inc
rm -f doc/src/layouts/stdFiles.lst
rm -f doc/src/layouts/textclass.lst

rm -f doc/src/started/DocDs.*
rm -f doc/src/started/line.lyx
rm -f doc/src/started/tango1.jpg

#
#	lib directories
#


rm -f lib/cpp/client/README
rm -Rf lib/cpp/server/winnt_lib
rm -f lib/cpp/server/idl/idl2cpp
mv lib/cpp/server/idl/tangoSK.cpp lib/cpp/server/tangoSK.cpp
mv lib/cpp/server/idl/tangoDynSK.cpp lib/cpp/server/tangoDynSK.cpp
rm -f cpp/lib/server/w32win.cpp
rm -f cpp/lib/server/w32win.h
rm -f lib/cpp/server/ntservice.cpp

rm -f lib/idl/idl2cpp

rm -Rf lib/cpp/log4tango/autom4te.cache
rm -f lib/cpp/log4tango/make-install.sh
rm -Rf lib/cpp/log4tango/msvc6
rm -Rf lib/cpp/log4tango/msvc7
rm -Rf lib/cpp/log4tango/msvc8
rm -Rf lib/cpp/log4tango/msvc9

#
#	utils directories
#

rm -f utils/notifd2db/Makefile
rm -Rf utils/notifd2db/winnt

rm -f utils/tango_admin/Makefile


