//=============================================================================
//
// file :        TemplateDevServ.h
//
// description : Include for the TemplateDevServ class.
//
// project :     TANGO
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================
#ifndef _TEMPLATEDEVSERV_H
#define _TEMPLATEDEVSERV_H

#include <tango.h>
//using namespace Tango;

 //	Add your own constant definitions here.
 //-----------------------------------------------


namespace TemplateDevServ_ns
{

class TemplateDevServ: public Tango::Device_4Impl
{
public :
	//	Add your own data members here
	//-----------------------------------------


	//	Here is the Start of the automatic code generation part
	//-------------------------------------------------------------
/**
 *	@name attributes
 *	Attribute member data.
 */
//@{
//@}

/**
 *	@name Device properties
 *	Device property member data.
 */
//@{
//@}

/**@name Constructors
 * Miscellaneous constructors */
//@{
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device Name
 */
	TemplateDevServ(Tango::DeviceClass *cl,string &s);
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device Name
 */
	TemplateDevServ(Tango::DeviceClass *cl,const char *s);
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device name
 *	@param d	Device description.
 */
	TemplateDevServ(Tango::DeviceClass *cl,const char *s,const char *d);
//@}

/**@name Destructor
 * Only one destructor is defined for this class */
//@{
/**
 * The object destructor.
 */
	~TemplateDevServ() {delete_device();};
/**
 *	will be called at device destruction or at init command.
 */
	void delete_device();
//@}


/**@name Miscellaneous methods */
//@{
/**
 *	Initialize the device
 */
	virtual void init_device();
/**
 *	Always executed method before execution command method.
 */
	virtual void always_executed_hook();



//@}

	//	Here is the end of the automatic code generation part
	//-------------------------------------------------------------



protected :
	//	Add your own data members here
	//-----------------------------------------
};

}	// namespace_ns

#endif	// _TEMPLATEDEVSERV_H
